#!/usr/bin/env bash
#
# +----------------------------------------------------------------------------+
# | ./motd.sh/modules/00-banner                                                |
# +----------------------------------------------------------------------------+
# |       Usage: ---                                                           |
# | Description: MOTD module to print hostname                                 |
# |    Requires: MOTD                                                          |
# |       Notes: ---                                                           |
# |      Author: Waldemar Schroeer                                             |
# |     Company: Rechenzentrum Amper                                           |
# |     Version: 1.1                                                           |
# |     Created: 2021-03-29                                                    |
# |    Revision: 2026-04-21                                                    |
# |                                                                            |
# | Copyright © 2022 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# +----------------------------------------------------------------------------+

set -euo pipefail
source "${PREFIX}/libexec/motd.sh.framework"

# Check if module is enabled
[[ -z "{$MOD_BANNER_RUN+x}" ]] && exit 0
[[ ! "$MOD_BANNER_RUN" = "true" ]] && exit 0

# Check if mode and font is set, if not then set default values.
if [ -z "${MOD_BANNER_PRINT+x}" ]; then
    MOD_BANNER_PRINT="FQDN"
fi
if [ -z "${MOD_BANNER_FONT+x}" ]; then
    MOD_BANNER_FONT="standard"
fi

hostname="${HOSTNAME:-$(hostname)}"
if [ "$MOD_BANNER_PRINT" = "HOSTNAME" ]; then
    out="${CA}$(figlet -w ${WIDTH} -c -f ${MOD_BANNER_FONT} ${hostname%%.*})${CN}"
else
    out="${CA}$(figlet -w ${WIDTH} -c -f ${MOD_BANNER_FONT} $hostname)${CN}"
fi

print_columns "" "$out"
# +----- End ------------------------------------------------------------------+
