#!/usr/bin/env bash
#
# +----------------------------------------------------------------------------+
# | ./motd.sh/modules/00-datetime                                              |
# +----------------------------------------------------------------------------+
# |       Usage: ---                                                           |
# |       Notes: ---                                                           |
# | Description: MOTD module to show date and time                             |
# |    Requires: MOTD                                                          |
# |      Author: Waldemar Schroeer                                             |
# |     Company: Rechenzentrum Amper                                           |
# |     Version: 1.1                                                           |
# |     Created: 2021-03-29                                                    |
# |    Revision: 2026-04-21                                                    |
# |                                                                            |
# | Copyright © 2022 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# +----------------------------------------------------------------------------+

set -euo pipefail
source "${PREFIX}/libexec/motd.sh.framework"

# Check if module is enabled
[[ -z "${MOD_DATETIME_RUN+x}" ]] && exit 0
[[ ! "$MOD_DATETIME_RUN" = "true" ]] && exit 0

get_DateTime () {
    figlet -f big -w ${WIDTH} -c $(date "+%H:%M")
    figlet -f small -w ${WIDTH} -c $(date "+%d.%m.%Y")
}


# Call function atest and put output into variable.
out="$(get_DateTime)"

# Call function "print_columns" from framewark.sh.
print_columns "Time" "$out"
# +----- End ------------------------------------------------------------------+
