#!/usr/bin/env bash
#
# +----------------------------------------------------------------------------+
# | ./motd.sh/modules/10-user                                                  |
# +----------------------------------------------------------------------------+
# |       Usage: ---                                                           |
# | Description: MOTD module to show current user and last logins              |
# |    Requires: MOTD                                                          |
# |       Notes: ---                                                           |
# |      Author: Waldemar Schroeer                                             |
# |     Company: Rechenzentrum Amper                                           |
# |     Version: 1.1                                                           |
# |     Created: 2021-03-29                                                    |
# |    Revision: 2026-04-21                                                    |
# |                                                                            |
# | Copyright © 2022 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# +----------------------------------------------------------------------------+

set -euo pipefail
source "${PREFIX}/libexec/motd.sh.framework"

# Check if module is enabled
[[ -z "{$MOD_USER_RUN+x}" ]] && exit 0
[[ ! "$MOD_USER_RUN" = "true" ]] && exit 0

user=${USER:-$(id -un)}
hostname=${HOSTNAME:-$(hostname)}

user_Log () {
    echo "${user}@${hostname}"
    if [ "$MOD_USER_LAST" = "true" ]; then
        echo -e "Last successfull logins:"
        while read -r login lipaddr lday lmonth ldate ltime; do
        echo "$(print_split "${WIDTH}" "${login}" "${lipaddr} ${lday} ${lmonth} ${ldate} ${ltime}")"
        done <<< "$(last -n 5 | head -5 | awk '($1 != "reboot") {print $1,$3,$4,$5,$6,$7}')"
    fi
}

out="$(user_Log)"
print_columns "Logged as" "$out"
# +----- End ------------------------------------------------------------------+
