#!/usr/bin/env bash
#
# +----------------------------------------------------------------------------+
# | ./motd.sh/modules/11-os                                                    |
# +----------------------------------------------------------------------------+
# |       Usage: ---                                                           |
# | Description: MOTD module to show OS information                            |
# |    Requires: MOTD                                                          |
# |       Notes: ---                                                           |
# |      Author: Waldemar Schroeer                                             |
# |     Company: Rechenzentrum Amper                                           |
# |     Version: 1.1                                                           |
# |     Created: 2021-03-29                                                    |
# |    Revision: 2026-04-21                                                    |
# |                                                                            |
# | Copyright © 2022 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# +----------------------------------------------------------------------------+

set -euo pipefail
source "$BASE_DIR/framework.sh"

# Check if module is enabled
[[ -z "{$MOD_OS_RUN+x}" ]] && exit 0
[[ ! "$MOD_OS_RUN" = "true" ]] && exit 0

# Check for mode, if not set then set it to false
if [ -z "${MOD_OS_VERBOSE+x}" ]; then
    MOD_OS_VERBOSE="false"
fi

os_Info () {
    if [ "$MOD_OS_VERBOSE" = "true" ]; then
        print_split "${WIDTH}" "${os} ${kernel}" "${arch}"
    else
        echo "$os"
    fi
}

out="$(os_Info)"
print_columns "OS" "$out"
# +----- End ------------------------------------------------------------------+
