#!/usr/bin/env bash
#
# +----------------------------------------------------------------------------+
# | ./motd.sh/modules/12-ip                                                    |
# +----------------------------------------------------------------------------+
# |       Usage: ---                                                           |
# | Description: MOTD module to show current IP Address                        |
# |    Requires: MOTD                                                          |
# |       Notes: ---                                                           |
# |      Author: Waldemar Schroeer                                             |
# |     Company: Rechenzentrum Amper                                           |
# |     Version: 1.1                                                           |
# |     Created: 2021-03-29                                                    |
# |    Revision: 2026-05-13                                                    |
# |                                                                            |
# | Copyright © 2022 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# +----------------------------------------------------------------------------+

set -euo pipefail
source "${BASEDIR}/motd.sh.framework"

# Check if module is enabled
[[ -z "${MOD_IP_RUN+x}" ]] && exit 0
[[ ! "$MOD_IP_RUN" = "true" ]] && exit 0

case $os in
    Linux*)
        mapfile -t ips_v4 < <(ip a | "${awk}" '/inet / && /scope/ {split($2, arr, /\//); print arr[1]}')
        mapfile -t ips_v6 < <(ip a | "${awk}" '/inet6/ && /scope/ {split($2, arr, /\//); print arr[1]}')
    ;;

    FreeBSD)
        mapfile -t ips_v4 < <(ifconfig | "${awk}" '/inet / && /broadcast/ {split($2, arr, /\//); print arr[1]}')
        mapfile -t ips_v6 < <(ifconfig | "${awk}" '/inet6/ && /scope/ {split($2, arr, /\//); print arr[1]}')
    ;;

    SunOS)
        mapfile -t ips_v4 < <(ifconfig -a | "${awk}" '/inet / && /broadcast/ {split($2, arr, /\//); print arr[1]}')
        mapfile -t ips_v6 < <(ifconfig -a | "${awk}" '/inet6/ && /scope/ {split($2, arr, /\//); print arr[1]}')
    ;;
esac

text4="$(printf '%s\n' "${ips_v4[@]}")"
text6="$(printf '%s\n' "${ips_v6[@]}")"

print_columns "IPv4 addresses" "${text4}"
print_columns "IPv6 addresses" "${text6}"
# +----- End ------------------------------------------------------------------+
