#!/usr/bin/env bash
#
# +----------------------------------------------------------------------------+
# | ./motd.sh/modules/13-public-ip                                             |
# +----------------------------------------------------------------------------+
# |       Usage: ---                                                           |
# | Description: MOTD module to show current IP addresses                      |
# |    Requires: MOTD                                                          |
# |       Notes: ---                                                           |
# |      Author: Waldemar Schroeer                                             |
# |     Company: Rechenzentrum Amper                                           |
# |     Version: 1.1                                                           |
# |     Created: 2021-04-20                                                    |
# |    Revision: 2026-04-21                                                    |
# |                                                                            |
# | Copyright © 2022 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# +----------------------------------------------------------------------------+

set -euo pipefail
source "${PREFIX}/libexec/motd.sh.framework"

# Check if module is enabled
[[ -z "${MOD_PUBLIC_IP_RUN=x}" ]] && exit 0
[[ ! "$MOD_PUBLIC_IP_RUN" = "true" ]] && exit 0

get_Public_IP () {
    # Check if curl is installed
    if ! command -v curl &> /dev/null; then
        echo "curl is not installed."
    else
        curl --silent http://ifconfig.me/ip
    fi
}

out="$(print_wrap $WIDTH "$(get_Public_IP)")"
print_columns "Public IP address" "$out"
# +----- End ------------------------------------------------------------------+
