#!/usr/bin/env bash
#
# +----------------------------------------------------------------------------+
# | ./motd.sh/modules/20-uptime                                                |
# +----------------------------------------------------------------------------+
# |       Usage: ---                                                           |
# | Description: MOTD module to show current uptime                            |
# |    Requires: MOTD                                                          |
# |       Notes: ---                                                           |
# |      Author: Waldemar Schroeer                                             |
# |     Company: Rechenzentrum Amper                                           |
# |     Version: 1.1                                                           |
# |     Created: 2021-03-29                                                    |
# |    Revision: 2026-04-21                                                    |
# |                                                                            |
# | Copyright © 2022 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# +----------------------------------------------------------------------------+

set -euo pipefail
source "${PREFIX}/libexec/motd.sh.framework"

# Check if module is enabled
[[ -z "{$MOD_UPTIME_RUN+x}" ]] && exit 0
[[ ! "$MOD_UPTIME_RUN" = "true" ]] && exit 0

case $os in
    Linux*)
        IFS=. read -r s _ < /proc/uptime
    ;;

    FreeBSD)
        s="$(sysctl -n kern.boottime)"
        s="${s#*=}"
        s="${s%,*}"
        s="$(($(date +%s) - s))"
    ;;

    SunOS)
        IFS='	.' read -r _ s _ <<-EOF
            $(kstat -p unix:0:system_misc:snaptime)
EOF
    ;;
esac

# Get days, hours and minutes.
d="$((s / 60 / 60 / 24))"
h="$((s / 60 / 60 % 24))"
m="$((s / 60 % 60))"
out="${d}d ${h}h ${m}m"

print_columns "Uptime" "$out"
# +----- End ------------------------------------------------------------------+
