#!/usr/bin/env bash
#
# +----------------------------------------------------------------------------+
# | ./motd.sh/modules/30-load                                                  |
# +----------------------------------------------------------------------------+
# |       Usage: ---                                                           |
# | Description: MOTD module to show current load                              |
# |    Requires: MOTD                                                          |
# |       Notes: ---                                                           |
# |      Author: Waldemar Schroeer                                             |
# |     Company: Rechenzentrum Amper                                           |
# |     Version: 1.1                                                           |
# |     Created: 2021-03-29                                                    |
# |    Revision: 2026-04-21                                                    |
# |                                                                            |
# | Copyright © 2022 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# +----------------------------------------------------------------------------+

set -euo pipefail
source "${BASEDIR}/motd.sh.framework"

# Check if module is enabled
[[ -z "${MOD_LOAD_RUN+x}" ]] && exit 0
[[ ! "$MOD_LOAD_RUN" = "true" ]] && exit 0

case $os in
    Linux*)
        ftext="load average:"
        nproc="$(nproc)"
    ;;

    FreeBSD)
        ftext="load averages:"
        nproc="$(sysctl -n hw.ncpu)"
    ;;

    SunOS)
        ftext="load average:"
        nproc="$(psrinfo -p)"
    ;;
esac

loads="$(uptime | "$awk" -F "$ftext" '{print $2}' | cut -d ',' -f '1,2,3' | "$sed" 's/,//g; s/^ //g')"
warning_threshold=$("$bc" -l <<< "$nproc * 0.9")
error_threshold=$("$bc" -l <<< "$nproc * 1.5")

out=""
for load in $loads; do
    out+="$(print_color $load $load $warning_threshold $error_threshold), "
done

print_columns "Load average" "${out::-2}"
# +----- End ------------------------------------------------------------------+
