#!/usr/bin/env bash
#
# +----------------------------------------------------------------------------+
# | ./motd.sh/modules/32-disk                                                  |
# +----------------------------------------------------------------------------+
# |       Usage: ---                                                           |
# | Description: MOTD module to print disk information                         |
# |    Requires: MOTD                                                          |
# |       Notes: ---                                                           |
# |      Author: Waldemar Schroeer                                             |
# |     Company: Rechenzentrum Amper                                           |
# |     Version: 1.1                                                           |
# |     Created: 2021-03-29                                                    |
# |    Revision: 2026-04-21                                                    |
# |                                                                            |
# | Copyright © 2022 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# +----------------------------------------------------------------------------+

set -euo pipefail
source "${BASEDIR}/motd.sh.framework"

# Check if module is enabled
[[ -z "${MOD_DISK_RUN+x}" ]] && exit 0
[[ ! "$MOD_DISK_RUN" = "true" ]] && exit 0

disks=($(df | grep '^/dev\|//' | cut -d' ' -f1 ))
all_disks_stats="$(df -h)"

out=""
for disk in "${disks[@]}"; do
    grep -q "$disk\s" <<< $all_disks_stats || continue

    stats="$(awk -v pat="$disk" '$0~pat {print $2,$3,$4,$5,$6}' <<< "$all_disks_stats")"
    IFS=" " read -r total used free percentage mountpoint <<< "$stats"

    device=($(echo $disk | "$sed" -r 's/\/dev//g;s/\/mapper//g;s/^\/\/(.*)\///g;s/^.\{1\}//'))
    left_label="$device () - $used used, $free free"
    right_label="/ $total"
    free_width=$(( $WIDTH - ${#left_label} - ${#right_label} - 1 ))
    mountpoint=$(print_truncate "$mountpoint" $free_width "start")
    left_label="$device ($mountpoint) - $used used, $free free"

    label="$(print_split $WIDTH "$left_label" "$right_label")"
    out+="$label\n$(print_bar $WIDTH ${percentage::-1})\n"
done

print_columns "Disk space" "${out::-2}"
# +----- End ------------------------------------------------------------------+
