#!/usr/bin/env bash
#
# +----------------------------------------------------------------------------+
# | ./motd.sh/modules/33-services                                              |
# +----------------------------------------------------------------------------+
# |       Usage: ---                                                           |
# | Description: MOTD module to monitor services                               |
# |    Requires: MOTD                                                          |
# |       Notes: ---                                                           |
# |      Author: Waldemar Schroeer                                             |
# |     Company: Rechenzentrum Amper                                           |
# |     Version: 1.1                                                           |
# |     Created: 2021-03-29                                                    |
# |    Revision: 2026-04-21                                                    |
# |                                                                            |
# | Copyright © 2022 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# +----------------------------------------------------------------------------+

set -euo pipefail
source "${BASEDIR}/motd.sh.framework"

# Check if module is enabled
[[ -z "${MOD_SERVICES_RUN+x}" ]] && exit 0
[[ ! "$MOD_SERVICES_RUN" = "true" ]] && exit 0

case $os in
    Linux*)
        statuses=()
        for key in "${!services[@]}"; do
            # systemctl is-active returns non-zero code if service is inactive
            set +e; status=$(systemctl is-active ${services[$key]}); set -e
            statuses+=("$(print_status "$key" "$status")")
        done
        out="$(print_wrap $WIDTH "${statuses[@]}")"
    ;;

    FreeBSD)
        statuses=()
        for key in "${!services[@]}"; do
            # service status returns non-zero code if service is inactive
            set +e; status=$(service ${services[$key]} status > /dev/null 2>&1 && echo "active" || echo "inactive"); set -e
            statuses+=("$(print_status "$key" "$status")")
        done
        out="$(print_wrap $WIDTH "${statuses[@]}")"
    ;;

    SunOS)
        out="Sorry, not implemented for SunOS."
    ;;
esac
print_columns "Services" "$out"
# +----- End ------------------------------------------------------------------+
