#!/usr/bin/env bash
#
# +----------------------------------------------------------------------------+
# | ./motd.sh/modules/34-cert                                                  |
# +----------------------------------------------------------------------------+
# |       Usage: ---                                                           |
# | Description: MOTD module to Check validity of certificates                 |
# |    Requires: MOTD                                                          |
# |       Notes: ---                                                           |
# |      Author: Waldemar Schroeer                                             |
# |     Company: Rechenzentrum Amper                                           |
# |     Version: 1.1                                                           |
# |     Created: 2021-05-30                                                    |
# |    Revision: 2026-04-21                                                    |
# |                                                                            |
# | Copyright © 2022 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# +----------------------------------------------------------------------------+

set -euo pipefail
source "${PREFIX}/libexec/motd.sh.framework"

# Check if module is enabled
[[ -z "${MOD_CERT_RUN+x}" ]] && exit 0
[[ ! "$MOD_CERT_RUN" = "true" ]] && exit 0

# Make sure that FreeBSD is using GNU date
date="date"
[[ "$os" = "FreeBSD" ]] && date="gdate"

cert_validity () {
    currentTime=$(${date} +%s)
    for sslcheck in ${!certhostlist[@]}; do
        IFS=";" read -r shortname fqdn port <<< ${certhostlist[$sslcheck]}
        certTime=$(openssl s_client -servername ${fqdn} -connect ${fqdn}:${port} < /dev/null 2>/dev/null | openssl x509 -noout -enddate 2>/dev/null | cut -d= -f2)
        certLineTime=$(${date} -d "${certTime}" +"%a %b %d %Y")
        certTimestamp=$(${date} -d "${certTime}" +%s)
        if [ "${certTimestamp}" -ge "${currentTime}" ]; then
            sign="${CO}${CERTCHAROK}${CN}"
        else
            sign="${CE}${CERTCHAREX}${CN}"
        fi
        echo "$(print_split "${WIDTH}" "${sign}${shortname}" "$certLineTime")"
    done
}

# Call function validity and put output into variable.
out="$(cert_validity)"

# Call function "print_columns" from framewark.sh.
print_columns "Certificate Validity" "$out"
# +----- End ------------------------------------------------------------------+
