#!/usr/bin/env bash
#
# +----------------------------------------------------------------------------+
# | ./motd.sh/modules/12-ip                                                    |
# +----------------------------------------------------------------------------+
# |       Usage: ---                                                           |
# | Description: MOTD module to print temperatures                             |
# |    Requires: MOTD                                                          |
# |       Notes: ---                                                           |
# |      Author: Waldemar Schroeer                                             |
# |     Company: Rechenzentrum Amper                                           |
# |     Version: 1.1                                                           |
# |     Created: 2021-03-29                                                    |
# |    Revision: 2026-05-13                                                    |
# |                                                                            |
# | Copyright © 2022 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# +----------------------------------------------------------------------------+

set -euo pipefail
source "${BASEDIR}/motd.sh.framework"

# Check if module is enabled
[[ -z "${MOD_TEMPERATURES_RUN+x}" ]] && exit 0
[[ ! "$MOD_TEMPERATURES_RUN" = "true" ]] && exit 0

temp_intel() {
    local cores out

    cores="$(echo "${sensors_output}" | grep Core | awk '{printf "%s ", $3} {printf "%s %s %s\n", $6, $9, $12}' | tr -d '+°C,)')"
    out=""

    while IFS= read -r line; do
        IFS=" " read -r current high critical <<< "${line}"

        if [[ "${high}" == "${critical}" ]]; then
            high=$(bc -l <<< "${high} - 20")
        fi

        out+="$(print_color "${current}°C" "${current}" "${high}" "${critical}"), "
    done <<< "${cores}"

    echo "${out::-2}"
}

temp_amd() {
    echo "${sensors_output}" | awk '/Tdie/ {print $2}' | tr -d '+'
}

sensors_output="$(sensors)"

if grep -q 'Tdie' <<< "${sensors_output}"; then
    temps=$(temp_amd)
else
    temps=$(temp_intel)
fi

print_columns "Temperatures" "${temps}"
# +----- End ------------------------------------------------------------------+
