#!/usr/bin/env bash
#
# +----------------------------------------------------------------------------+
# | ./motd.sh/modules/12-ip                                                    |
# +----------------------------------------------------------------------------+
# |       Usage: ---                                                           |
# | Description: MOTD module to print S.M.A.R.T informations                   |
# |    Requires: MOTD                                                          |
# |       Notes: ---                                                           |
# |      Author: Waldemar Schroeer                                             |
# |     Company: Rechenzentrum Amper                                           |
# |     Version: 1.1                                                           |
# |     Created: 2021-03-29                                                    |
# |    Revision: 2026-05-13                                                    |
# |                                                                            |
# | Copyright © 2022 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# +----------------------------------------------------------------------------+

# smartctl needs root privileges to access the S.M.A.R.T. information of the
# disks. To avoid asking for a password every time, you can add the following
# line to your sudoers file (using visudo):
#   username ALL=(root) NOPASSWD: /usr/sbin/smartctl
#   wiewaldi ALL=(root) NOPASSWD: /usr/local/sbin/smartctl

set -euo pipefail
source "${PREFIX}/libexec/motd.sh.framework"

# Check if module is enabled
[[ -z "${MOD_SMART_RUN+x}" ]] && exit 0
[[ ! "$MOD_SMART_RUN" = "true" ]] && exit 0

type smartctl > /dev/null 2>&1 || exit 1
# Check if the user can execute smartctl with sudo without any password
sudo -n smartctl --version > /dev/null 2>&1 || exit 1

# Disk list:
disks=$(lsblk | awk '($6=="disk") {print $1}')

statuses=()
for disk in ${disks}; do
    # Avoid getting an error if disk doesn't work with smart
    smart_result=$(sudo smartctl -H "/dev/${disk}" 2> /dev/null || true)
    smart_value="${CW}unavailable${CN}"

    if echo "${smart_result}" | grep -q '^SMART overall\|^SMART Health Status'; then
        smart_test=$(echo "${smart_result}" | grep '^SMART overall\|^SMART Health Status' | rev | cut -d ' ' -f1 | rev)

        if [[ "${smart_test}" == 'PASSED' ]]; then
            smart_value="${CO}${smart_test}${CN}"
        else
            smart_value="${CE}${smart_test}${CN}"
        fi
    fi

    statuses+=("${disk} ${smart_value}")
done

text=$(print_wrap "${WIDTH}" "${statuses[@]}")

print_columns "S.M.A.R.T." "${text}"
# +----- End ------------------------------------------------------------------+
