#!/usr/bin/env bash
#
# +----------------------------------------------------------------------------+
# | ./motd.sh/modules/60-weather                                               |
# +----------------------------------------------------------------------------+
# |       Usage: ---                                                           |
# | Description: MOTD module to show current weather                           |
# |    Requires: MOTD                                                          |
# |       Notes: ---                                                           |
# |      Author: Waldemar Schroeer                                             |
# |     Company: Rechenzentrum Amper                                           |
# |     Version: 1.1                                                           |
# |     Created: 2021-03-29                                                    |
# |    Revision: 2026-04-21                                                    |
# |                                                                            |
# | Copyright © 2022 Waldemar Schroeer                                         |
# |                  waldemar.schroeer(at)rz-amper.de                          |
# +----------------------------------------------------------------------------+

set -euo pipefail
source "${PREFIX}/libexec/motd.sh.framework"

# Check if module is enabled
[[ ! "$MOD_WEATHER_RUN" = "true" ]] && exit 0

# Check if location is set. If not then use "Berlin" as location.
[[ -z "${MOD_WEATHER_LOCATION+x}" ]] && MOD_WEATHER_LOCATION="Berlin"
[[ -z "${MOD_WEATHER_OPTIONS+x}" ]] && MOD_WEATHER_OPTIONS="?0?F?Q"

get_Weather () {
    # Check if curl is installed
    if ! command -v curl &> /dev/null; then
        echo "curl is not installed."
    else
        curl --silent http://wttr.in/${MOD_WEATHER_LOCATION}${MOD_WEATHER_OPTIONS[@]}
    fi
}

out=$(get_Weather)
print_columns "Current Weather" "$out"
# +----- End ------------------------------------------------------------------+
